export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST'
export const USER_CREATE_SEUCCESS = 'USER_CREATE_SEUCCESS'
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SEUCCESS = 'USER_DETAILS_SEUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SEUCCESS = 'USER_LIST_SEUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SEUCCESS = 'USER_DELETE_SEUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SEUCCESS = 'USER_UPDATE_SEUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
